### ISSUE TITLE
having trouble running

### ISSUE THREAD

**Issue by magg** [palvaro/molly#9]
Hey guys

Have you run into this error?

```
sbt "run-main edu.berkeley.cs.boom.molly.SyncFTChecker \
    src/test/resources/examples_ft/delivery/simplog.ded \
    src/test/resources/examples_ft/delivery/deliv_assert.ded \
    --EOT 4 \
    --EFF 2 \
    --nodes a,b,c \
    --crashes 0 \
    --prov-diagrams"
[info] Loading project definition from /home/magg/molly/project
[info] Loading project definition from /home/magg/.sbt/0.13/staging/9e27883a6943bbaa3b1e/scalaz3/project
[info] Set current project to molly (in build file:/home/magg/molly/)
[info] Running edu.berkeley.cs.boom.molly.SyncFTChecker src/test/resources/examples_ft/delivery/simplog.ded src/test/resources/examples_ft/delivery/deliv_assert.ded --EOT 4 --EFF 2 --nodes a,b,c --crashes 0 --prov-diagrams
[error] (run-main-0) java.lang.UnsatisfiedLinkError: libc4.so: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: libc4.so: cannot open shared object file: No such file or directory
	at jnr.ffi.provider.jffi.NativeLibrary.loadNativeLibraries(NativeLibrary.java:87)
	at jnr.ffi.provider.jffi.NativeLibrary.getNativeLibraries(NativeLibrary.java:70)
	at jnr.ffi.provider.jffi.NativeLibrary.getSymbolAddress(NativeLibrary.java:49)
	at jnr.ffi.provider.jffi.NativeLibrary.findSymbolAddress(NativeLibrary.java:59)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:117)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:59)
	at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:43)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:265)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:244)
	at edu.berkeley.cs.boom.molly.wrappers.C4Wrapper$.<init>(C4Wrapper.scala:51)
	at edu.berkeley.cs.boom.molly.wrappers.C4Wrapper$.<clinit>(C4Wrapper.scala)
	at edu.berkeley.cs.boom.molly.wrappers.C4Wrapper.run(C4Wrapper.scala:17)
	at edu.berkeley.cs.boom.molly.Verifier.<init>(Verifier.scala:71)
	at edu.berkeley.cs.boom.molly.SyncFTChecker$.check(SyncFTChecker.scala:78)
	at edu.berkeley.cs.boom.molly.SyncFTChecker$$anonfun$main$2.apply(SyncFTChecker.scala:105)
	at edu.berkeley.cs.boom.molly.SyncFTChecker$$anonfun$main$2.apply(SyncFTChecker.scala:102)
	at scala.Option.map(Option.scala:146)
	at edu.berkeley.cs.boom.molly.SyncFTChecker$.main(SyncFTChecker.scala:102)
	at edu.berkeley.cs.boom.molly.SyncFTChecker.main(SyncFTChecker.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last molly/compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last molly/compile:runMain for the full output.
[error] (molly/compile:runMain) Nonzero exit code: 1
[error] Total time: 1 s, completed Jan 11, 2017 3:37:38 PM
```

Any ideas on how to solve it? I'm using Ubuntu 16.10 as my OS

**Comment by magg** [comment]
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/magg/molly/lib/c4/build/src/libc4/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/magg/molly/lib/z3/build
solve the issue


but then I get

```

 sbt "run-main edu.berkeley.cs.boom.molly.SyncFTChecker \             
    src/test/resources/examples_ft/delivery/simplog.ded \
    src/test/resources/examples_ft/delivery/deliv_assert.ded \
    --EOT 4 \
    --EFF 2 \
    --nodes a,b,c \
    --crashes 0 \
    --prov-diagrams"
[info] Loading project definition from /home/magg/molly/project
[info] Loading project definition from /home/magg/.sbt/0.13/staging/9e27883a6943bbaa3b1e/scalaz3/project
[info] Set current project to molly (in build file:/home/magg/molly/)
[info] Running edu.berkeley.cs.boom.molly.SyncFTChecker src/test/resources/examples_ft/delivery/simplog.ded src/test/resources/examples_ft/delivery/deliv_assert.ded --EOT 4 --EFF 2 --nodes a,b,c --crashes 0 --prov-diagrams
Local address = tcp:bodhidharma:42997
c4: Using base_dir = /home/magg/c4_home/tcp_42997
2017-01-11 16:15:49 WARN  Verifier - DO verify
[error] (run-main-0) java.lang.UnsatisfiedLinkError: unknown
java.lang.UnsatisfiedLinkError: unknown
	at jnr.ffi.provider.jffi.AsmRuntime.newUnsatisifiedLinkError(AsmRuntime.java:40)
	at z3.Z3Interface$jnr$ffi$1.Z3_mk_config(Unknown Source)
	at z3.scala.Z3Config.<init>(Z3Config.scala:6)
	at edu.berkeley.cs.boom.molly.derivations.Z3Solver$.solve(Z3Solver.scala:35)
	at edu.berkeley.cs.boom.molly.derivations.Solver$$anonfun$6.apply(Solver.scala:50)
	at edu.berkeley.cs.boom.molly.derivations.Solver$$anonfun$6.apply(Solver.scala:50)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at edu.berkeley.cs.boom.molly.derivations.Solver$class.solve(Solver.scala:50)
	at edu.berkeley.cs.boom.molly.derivations.Z3Solver$.solve(Z3Solver.scala:11)
	at edu.berkeley.cs.boom.molly.Verifier.verify(Verifier.scala:174)
	at edu.berkeley.cs.boom.molly.SyncFTChecker$.check(SyncFTChecker.scala:82)
	at edu.berkeley.cs.boom.molly.SyncFTChecker$$anonfun$main$2.apply(SyncFTChecker.scala:105)
	at edu.berkeley.cs.boom.molly.SyncFTChecker$$anonfun$main$2.apply(SyncFTChecker.scala:102)
	at scala.Option.map(Option.scala:146)
	at edu.berkeley.cs.boom.molly.SyncFTChecker$.main(SyncFTChecker.scala:102)
	at edu.berkeley.cs.boom.molly.SyncFTChecker.main(SyncFTChecker.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last molly/compile:runMain for the full output.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa238651b4d, pid=26587, tid=0x00007fa1ed94a700
#
# JRE version: OpenJDK Runtime Environment (8.0_111-b14) (build 1.8.0_111-8u111-b14-2ubuntu0.16.10.2-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.111-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x13ab4d]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/magg/molly/hs_err_pid26587.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
```

**Comment by magg** [comment]
fixed by export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./lib/c4/build/src/libc4/:./lib/z3/build/z3-dist/lib/

sorry not a bug
